import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
const browser = await chromium.launch({ headless: false, channel: 'chromium', args: ['--window-position=968,0','--window-size=904,1040','--ozone-platform=x11','--ignore-gpu-blocklist','--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required'] });
const page = await browser.newPage({ viewport: { width: 888, height: 930 } });
const errors = []; page.on('pageerror', e => errors.push(e.message)); page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
await page.route('**/@vite/client', route => route.fulfill({ contentType:'text/javascript', body:'' }));
await mkdir('/tmp/ashdrive-shots', {recursive:true});
await page.goto('http://localhost:5173/apps/ashdrive/');
await page.waitForFunction(() => window.__app?.ready, {timeout:60000});
await page.waitForTimeout(3000);
await page.screenshot({path:'/tmp/ashdrive-shots/title.png'});
console.log('TITLE', await page.evaluate(() => window.__app));
await page.getByRole('button',{name:'DEPLOY BIKE'}).click();
await page.keyboard.down('w');
await page.waitForTimeout(2500); await page.keyboard.up('w');
await page.screenshot({path:'/tmp/ashdrive-shots/freeway.png'});
console.log('DRIVE', await page.evaluate(() => window.__app));
await page.keyboard.press('c'); await page.waitForTimeout(1500);
await page.screenshot({path:'/tmp/ashdrive-shots/cockpit.png'});
console.log('ERRORS', errors);
await page.waitForTimeout(5000);
await browser.close();
